# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :pxe_server do |pxe_server|

    pxe_server.vm.box = "debian/jessie64"
    pxe_server.vm.hostname = "pxe-server"
    pxe_server.ssh.username ='root'
    pxe_server.ssh.insert_key = 'true'
    pxe_server.ssh.forward_x11 = 'true'
    #using rsync to fix nfs issues
    pxe_server.vm.synced_folder "config", "/config", type: "rsync"
    pxe_server.vm.network "private_network", ip: "192.168.0.254", libvirt__network_name: "pxe_network", :libvirt__dhcp_enabled => false, virtualbox__intnet: "pxe_network"

    pxe_server.vm.provider :libvirt do |libvirt|
      libvirt.cpu_mode = 'host-passthrough'
      libvirt.memory = '1024'
      libvirt.cpus = '1'
    end

    pxe_server.vm.provider :virtualbox do |vb|
      vb.memory = '1024'
      vb.cpus = '1'
    end

    pxe_server.vm.provision "shell", path: "config/setup.sh"

  end
end
